### ISSUE TITLE
Stop working / G3 latest cutting edge / MacOs Catalina 10.15.7

### ISSUE THREAD

**Issue by etunni** [mekkablue/MagicRemove#1]
Hi,
This is the message ar Macro Window.

```
Magic Remover Exception:
list index out of range

Magic Remover Traceback:
Traceback (most recent call last):
  File "plugin.py", line 125, in eraseSelectedItemsOnAllMasters_
    path = thisLayer.paths[pathIndex]
  File "GlyphsApp/GlyphsApp/__init__.py", line 460, in GSProxyShapes__getitem__
IndexError: list index out of range
```

**Comment by mekkablue** [comment]
I think this is fixed now.
